# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ByteowlsCapacitorSms' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ByteowlsCapacitorSms

   pod 'Capacitor', '~> 1.0.0-beta.16'

end
