require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ByteowlsCapacitorSms' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ByteowlsCapacitorSms
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'

end

post_install do |installer|
  assertDeploymentTarget(installer)
end
